// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function() {
    return require('through2').obj(function(file, enc, cb) {
      var PluginError, e, fail, replaceExtension, src, _ref;
      _ref = require('gulp-util'), PluginError = _ref.PluginError, replaceExtension = _ref.replaceExtension;
      fail = function(e) {
        return cb(new PluginError('gribbl', e));
      };
      if (file.isStream()) {
        return fail('streaming not supported');
      }
      if (file.isBuffer()) {
        try {
          src = String(file.contents);
          file.contents = new Buffer(jade.compile(src, {
            filename: file.path
          }));
        } catch (_error) {
          e = _error;
          return fail(e);
        }
      }
      file.path = replaceExtension(file.path, '.html');
      return cb(null, file);
    });
  };

}).call(this);
