// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function() {
    return require('through2').obj(function(file, enc, cb) {
      var $, PluginError, e, fail, path, replaceExtension, text, _ref;
      _ref = require('gulp-util'), PluginError = _ref.PluginError, replaceExtension = _ref.replaceExtension;
      fail = function(e) {
        return cb(new PluginError('gribbl', e));
      };
      if (file.isStream()) {
        return fail('streaming not supported');
      }
      path = file.path;
      file.path = replaceExtension(file.path, '.html');
      if (!file.isBuffer()) {
        return cb(null, file);
      }
      try {
        text = String(file.contents);
        if (/\.jade$/.test(path)) {
          text = require('jade').render(text, {
            filename: path,
            pretty: true
          });
        }
        $ = require('cheerio').load(text);
        $('script').each(function() {
          var el, subtext;
          el = $(this);
          subtext = el.text();
          subtext = "/* script tag munged by gribbl */\n" + subtext;
          return el.text(subtext);
        });
        text = $.html();
        text += '\n';
      } catch (_error) {
        e = _error;
        return fail(e);
      }
      file.contents = new Buffer(text);
      return cb(null, file);
    });
  };

}).call(this);
