// Generated by CoffeeScript 1.9.0
(function() {
  var gribbl, gulp;

  gulp = require('gulp');

  gribbl = require('./api');

  gulp.src(process.argv.slice(2)).pipe(gribbl()).pipe(gulp.dest('.'));

}).call(this);
